name: VSCode Tunnel
version: 1.3.3
slug: vscode-tunnel
description: VSCode Tunnel to have a full experience at vscode.dev.
url: https://github.com/uplandjacob/upland-ha-addons/tree/main/vscode-tunnel
stage: experimental
arch:
  - aarch64
  - amd64
boot: manual
init: false
image: ghcr.io/uplandjacob/upland-ha-addons-vscode-tunnel-{arch}
hassio_api: true
docker_api: true
map:
  - type: addon_config
    read_only: false
  - type: share
    read_only: false
  - type: media
    read_only: false
  - type: homeassistant_config
    read_only: false
  - type: all_addon_configs
    read_only: false
  - type: addons
    read_only: false

options:
  name: ''
  ghLogin: false
  memLimit: 1572864 # 1.5GB

schema:
  name: match([0-9a-zA-Z_-]*)
  ghLogin: bool
  memLimit: int
