name: VSCode Tunnel
version: 0.2.5
slug: vscode-tunnel
description: VSCode Tunnel to have a full experience at vscode.dev.
url: https://github.com/uplandjacob/upland-ha-addons/tree/main/vscode-tunnel
stage: experimental
arch:
  - armv7
  - aarch64
  - amd64
  - i386
boot: manual
init: false
image: ghcr.io/uplandjacob/upland-ha-addons-vscode-tunnel-{arch}
hassio_api: true
map:
  - type: addon_config
    read_only: false

options:
  name: ''
  ghLogin: ''

schema:
  name: match([0-9a-zA-Z_-]*)
  ghLogin: bool