name: Flask Server
version: 1.3.0
slug: flask
description: Addon to run a Flask web server in Home Assistant
url: https://github.com/uplandjacob/upland-ha-addons/tree/main/flask
stage: experimental
hassio_api: true
init: false
image: ghcr.io/uplandjacob/upland-ha-addons-flask-{arch}
arch:
  - amd64
  - aarch64
map:
  - type: addon_config
    read_only: false
  - type: share
    read_only: false

options:
  enableCelery: false
  enableCeleryBeat: false
  celeryApp: main
  celeryLogLevel: info

schema:
  enableCelery: bool
  enableCeleryBeat: bool
  celeryApp: str
  celeryLogLevel: list(debug|info|warning|error|critical|fatal)
  celeryBeatLogLevel: list(debug|info|warning|error|critical|fatal)?

ports:
  "5000/tcp": 5000
ports_description:
  "5000/tcp": "Flask server port"