name: Flask Dev Server
version: 1.3.13-dev-1.4.0-4
slug: flask-dev
description: Developer version of the Flask Addon to have a second server separate from your production server.
url: https://github.com/uplandjacob/upland-ha-addons/tree/main/flask-dev
stage: experimental
hassio_api: true
init: false
image: ghcr.io/uplandjacob/upland-ha-addons-flask-dev-{arch}
arch:
  - amd64
  - aarch64
map:
  - type: addon_config
    read_only: false
  - type: share
    read_only: false

options:
  enableCelery: false
  enableCeleryBeat: false
  celeryApp: main
  celeryLogLevel: info

schema:
  enableCelery: bool
  enableCeleryBeat: bool
  celeryApp: str?
  celeryLogLevel: list(debug|info|warning|error|critical|fatal)
  celeryBeatLogLevel: list(debug|info|warning|error|critical|fatal)?

ports:
  "5000/tcp": 5000
ports_description:
  "5000/tcp": "Flask server port"